# UTF-8
#
# Version information for Windows executable
# This helps with antivirus detection by providing proper metadata
#
# NOTE: This file should be regenerated by the build script using src/version.py
# The version numbers below should match src/version.py
# To update version: edit src/version.py and run the build script

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=(1, 2, 7, 0),
    prodvers=(1, 2, 7, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'EWExport Open Source Project'),
        StringStruct(u'FileDescription', u'EasyWorship to ProPresenter Converter - A tool for converting worship song databases'),
        StringStruct(u'FileVersion', u'1.2.7.0'),
        StringStruct(u'InternalName', u'ewexport'),
        StringStruct(u'LegalCopyright', u'Copyright (c) 2025 - MIT License'),
        StringStruct(u'OriginalFilename', u'ewexport.exe'),
        StringStruct(u'ProductName', u'EasyWorship to ProPresenter Converter'),
        StringStruct(u'ProductVersion', u'1.2.7.0'),
        StringStruct(u'Comments', u'Open source worship song converter tool. Source available at github.com/karllinder/ewexport'),
        StringStruct(u'LegalTrademarks', u''),
        StringStruct(u'PrivateBuild', u''),
        StringStruct(u'SpecialBuild', u'')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)